source/objects/SMS_Message__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS Message</relationshipLabel>
        <relationshipName>SMS_Message</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <description>Date the SMS was successfully sent.</description>
        <label>Date Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{0}</displayFormat>
        <label>SMS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/classes/SMSViewAllController.cls
public class SMSViewAllController {

    public List<SMS_Message__c> messages {get; set;}

    public SMSViewAllController(ApexPages.StandardController controller) {
        Contact con = (Contact)controller.getRecord();
        
        //Query all messges related to a contact, limit to 500
        messages = [select Id, Message__c, Status__c, Direction__c, Date_Sent__c from SMS_Message__c where Contact__c = :con.Id order by Date_Sent__c desc limit 500];
    }

}