source/objects/SMS_Message__c.object
<CustomObject>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <description>Date the SMS was successfully sent.</description>
        <label>Date Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sid__c</fullName>
        <label>Sid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{0}</displayFormat>
        <label>SMS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/classes/SMSStatusListenController.cls
public class SMSStatusListenController {
    
    /*This class is linked to page exposed as force.com site and listens for SMS delivery status callback */
    
    SMS_Message__c msg;

    public void updateStatus() {
        //Twilio passes all information as URL parameters so we can simply add these to a map and use as needed
        Map<String,String> parameters = ApexPages.currentPage().getParameters();
        
        //Find the message__c record that needs to be updated
        List<SMS_Message__c> messsages = [select Status__c from SMS_Message__c where Sid__c = :parameters.get('SmsSid')];
        if(messsages.size() > 0){
            msg = messsages[0];
            msg.Status__c = parameters.get('SmsStatus');
            
            //Updated date sent if messages was sent succcessfully
            if(parameters.get('SmsStatus') != null && parameters.get('SmsStatus').toLowerCase() == 'sent'){
            	msg.Date_Sent__c = system.now();
            }
        }
        
       	//Updated message if one was found
        if(msg != null){
            update msg;
        }
    }
}