src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SMS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Enabled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

source/objects/SMS_Message__c.object
<CustomObject>
    <fields>
        <fullName>AccountSid__c</fullName>
        <label>AccountSid</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS Message</relationshipLabel>
        <relationshipName>SMS_Message</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Sent__c</fullName>
        <description>Date the SMS was successfully sent.</description>
        <label>Date Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sid__c</fullName>
        <label>Sid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{0}</displayFormat>
        <label>SMS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Message</pluralLabel>
    <recordTypes>
        <fullName>Inbound</fullName>
        <active>true</active>
        <description>Record type inbound SMS messages.</description>
        <label>Inbound</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

source/objects/Twilio_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores information related to Twilio. Phone numbers, Account Sid, Auth Token, etc.</description>
    <fields>
        <fullName>Unsubscribe_Keywords__c</fullName>
        <inlineHelpText>Comma separated list of words that if user responds with will uncheck the SMS Enalbed field on Contact.</inlineHelpText>
        <label>Unsubscribe Keywords</label>
        <type>TextArea</type>
    </fields>
    <label>Twilio Settings</label>
</CustomObject>

source/classes/SMSInboundListenController.cls
public class SMSInboundListenController {
    
    public String response {get; set;}
    SMS_Message__c msg;
    Contact con;
 
    public void processMessage(){
        //Instantiate new message object
        msg = new SMS_Message__c();        
        
        //Setup default reponse
        response = '<Response><Sms>Thanks, you rock.</Sms></Response>'; 
            
        //Twilio passes all the data to this page in url parameters, get those and store in map  
        Map<String,String> parameters = ApexPages.currentPage().getParameters();    
        
        /*Attempt to locate contact in system with mobile number of inbound SMS, also query at least one
        SMS related to the contact. Will use this for dupe logic.*/
        List<Contact> consWithSMS = new List<Contact>();
        List<Contact> contacts = new List<Contact>(); 
        
        for(Contact con : [select Id, OwnerId, (Select Id from SMS_Message__r limit 1) from Contact where MobilePhone = :parameters.get('From')]){
            //Add contact to correct list based on if they have existing SMS messages attached to them
            if(con.SMS_Message__r.size() > 0){
                consWithSMS.add(con);
            }else{
                contacts.add(con);
            }
        } 
        
        //If there are contacts with existing sms messages use the first contact return
        if(consWithSMS.size() > 0){
            con = consWithSMS[0];
            msg.OwnerId = consWithSMS[0].OwnerId;
            msg.Contact__c = consWithSMS[0].Id;
        }else if(contacts.size() > 0){
            //Else attempt to use first contact with match phone but no existing messages
            con = contacts[0];
            msg.OwnerId = contacts[0].OwnerId;
            msg.Contact__c = contacts[0].Id;
        }      
        
        //Identify record type for inbound sms messages
        Id inboundRecordTypeId = [select Id from RecordType where DeveloperName = 'Inbound' AND sObjectType = 'SMS_Message__c' limit 1].Id;
        
        //Apply infromation from Twilio to SMS Message object before insertion
        msg.RecordTypeId = inboundRecordTypeId;
        msg.Sid__c = parameters.get('SmsSid');
        msg.AccountSid__c = parameters.get('AccountSid');
        msg.From__c = parameters.get('From');
        msg.To__c = parameters.get('To');
        msg.Message__c = parameters.get('Body');
        msg.Date_Sent__c = system.now();
        msg.Direction__c = 'Inbound';
        msg.Status__c = 'Unread';
        msg.Price__c = 0.02;
        
        //If user replied with STOP, make SMS_Enabled__c false on contact
        Set<String> unsubscribeWords = new Set<String>();        
        
        //Get and process unsubscribe keywords from custom settings, convert to lowercase
        Twilio_Settings__c settings = Twilio_Settings__c.getInstance('main');
        if(settings.Unsubscribe_Keywords__c != null){
            for(String s : settings.Unsubscribe_Keywords__c.split(',')){
                unsubscribeWords.add(s.toLowerCase());
            }   
        }
        
        //If messages is the same as one of the unsubscribe keyworks uncheck SMS_Enabled field
        if(unsubscribeWords.contains(msg.Message__c.toLowerCase()) && con != null){
            response = '<Response><Sms>Okay, we won\'t annoying you any more.</Sms></Response>'; 
            con.SMS_Enabled__c = false;
            update con;
        }
        
        //Only insert the new SMS message if there was a smsID present in URL, if not this request isn't coming from Twilio, ie: someone viewing the page
        if(msg.Sid__c != null){
        	insert msg;
        }
    }
}